apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: pushgateway
  labels:
    app: pushgateway
spec:
  selector:
    app: pushgateway
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: pushgateway
  labels:
    app: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:v1.8.0
        ports:
        - name: http
          containerPort: 9091
        resources:
          requests:
            # cpu: 50m
            memory: 100Mi
          limits:
            # cpu: 100m
            memory: 200Mi
