apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: test
  labels:
    app: backend
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hashicorp/http-echo
        args:
        - "-text=backend-test"
        ports:
        - containerPort: 5678
