apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: live
  labels:
    app: backend
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: live
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hashicorp/http-echo
        args:
        - "-text=backend-live"
        ports:
        - containerPort: 5678
