apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # namespace: monitoring
  name: influxdb-pvc
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
