apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            # - name: MYSQL_ALLOW_EMPTY_PASSWORD
            #   value: yes
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-superuser
                  key: password
          ports:
            - name: mysql
              containerPort: 3306
          # livenessProbe:
          #   exec:
          #     command:
          #     - mysqladmin
          #     - ping
          #     - -h 127.0.0.1
          #     - -u USER
          #     - -p PASSWORD
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          # readinessProbe:
          #   exec:
          #     command:
          #     - mysqladmin
          #     - ping
          #     - -h 127.0.0.1
          #     - -u USER
          #     - -p PASSWORD
          #   initialDelaySeconds: 5
          #   periodSeconds: 2
          #   timeoutSeconds: 1
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volume-claim
