apiVersion: v1
kind: ConfigMap
metadata:
  # namespace: monitoring
  name: telegraf
  labels:
    app: telegraf
data:
  telegraf.conf: |+
    [global_tags]
      dc = "fsn1"
    [agent]
      interval = "30s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "30s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      quiet = true
      logfile = ""
      omit_hostname = false
      hostname = "${HOSTNAME}"
    [[inputs.internal]]
      namepass = [
        "internal_agent"
      ]
    [[inputs.kernel]]
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.mem]]
    [[inputs.swap]]
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
    [[inputs.diskio]]
    # [[inputs.processes]]
    # [[inputs.system]]
    # [[inputs.prometheus]]
    #   urls = []
    #   metric_version = 2
    #   fieldpass = [
    #     "caddy_*",
    #     "process_*"
    #   ]
    # [[inputs.redis]]
    #   servers = [ "tcp://127.0.0.1:6379" ];
    #   # fieldpass = [ "keyspace_*" "used_*" "tracking_*" "io_threaed_*" ];

    [[inputs.x509_cert]]
      interval = "24h"
      sources = [
        "tcp://google.com:443"
      ]

    [[inputs.kubernetes]]
    url = "https://$HOSTIP:10250"
    bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
    # tls_ca = "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    # insecure_skip_verify = true

    # [[inputs.kube_inventory]]
    # url = "https://${KUBERNETES_SERVICE_HOST}"
    # bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
    # tls_ca = "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
    # insecure_skip_verify = true
    # namespace = ""

    [[outputs.file]]
    files = [ "/dev/null" ]

    [[outputs.health]]
    service_address = "http://127.0.0.1:8888"
