apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: infra
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: true  # allows access to host network
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          name: metrics
      resources:
        requests:
          # cpu: 50m
          memory: 100Mi
        limits:
          # cpu: 100m
          memory: 200Mi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: infra
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
  # namespaceSelector:
  #   matchNames:
  #     - ""
